version: "2.4"

x-runner-container:
  &runner-container
  privileged: true
  tmpfs:
    - /tmp
    - /run
    - /scratch
  # Set this flag to a value greater or less than the default of 1024
  # to increase or reduce the container's weight, and give it access to
  # a greater or lesser proportion of the host machine's CPU cycles.
  # This is only enforced when CPU cycles are constrained.
  cpu_shares: 768
  mem_limit: 16g
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io
    # container runners are only suitable for private repositories
    ACTIONS_RUNNER_GROUP: self-hosted-internal

x-runner-vm:
  &runner-vm
  privileged: true
  network_mode: host
  tmpfs:
    - /tmp
    - /run
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io
    ACTIONS_RUNNER_GROUP: self-hosted
    # limit each VM runner to 1/10th of host CPU count, rounded up to ^2
    CPU_PERCENT: 0.10
    # limit each VM runner to 1/10th of host memory GiB, rounded up to ^2
    MEMORY_PERCENT: 0.10

services:

  runner-container-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.14.6

  runner-container-2:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.14.6

  runner-focal-1:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2-focal

  runner-focal-2:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2-focal

  runner-jammy-1:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2

  runner-jammy-2:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2

  runner-jammy-3:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2

  runner-jammy-4:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2

  runner-jammy-5:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2

  runner-jammy-6:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.8.2

  # inspects the runner logs and sets the supervisor lock if jobs are running
  lock-manager:
    build: lock-manager
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena-engine.sock
