version: "2.4"

x-runner-container:
  &runner-container
  privileged: true
  tmpfs:
    - /tmp
    - /run
    - /scratch
  environment:
    GITHUB_ENTERPRISE: balena
    # register to the internal-only self-hosted runner group
    ACTIONS_RUNNER_GROUP: self-hosted-internal

x-runner-vm:
  &runner-vm
  privileged: true
  network_mode: host
  tmpfs:
    - /tmp
    - /run
    - /srv
  environment:
    GITHUB_ENTERPRISE: balena
    # register to the self-hosted runner group allowed on public repositories
    ACTIONS_RUNNER_GROUP: self-hosted
    # limit VM memory to 8GB, or the host total memory, whichever is lower
    MEM_SIZE_MIB: 8192

services:

  # container runners are only suitable for private repositories

  jammy-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.88

  jammy-2:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.88

  focal-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-focal

  focal-2:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-focal

  # focal-vm is the equivalent of ubuntu-20.04

  focal-vm-1:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-focal-vm

  focal-vm-2:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-focal-vm

  focal-vm-3:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-focal-vm

  focal-vm-4:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-focal-vm

  # jammy-vm is the equivalent of ubuntu-22.04(-latest)

  jammy-vm-1:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  jammy-vm-2:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  jammy-vm-3:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  jammy-vm-4:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  jammy-vm-5:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  jammy-vm-6:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  jammy-vm-7:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  jammy-vm-8:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.88-jammy-vm

  # inspects the runner logs and sets the supervisor lock if jobs are running
  lock-manager:
    build: lock-manager
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena-engine.sock
