version: "2.4"

x-runner-container:
  &runner-container
  privileged: true
  tmpfs:
    - /tmp
    - /run
    - /scratch
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    # register to the internal-only self-hosted runner group
    ACTIONS_RUNNER_GROUP: self-hosted-internal
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io

x-runner-vm:
  &runner-vm
  privileged: true
  network_mode: host
  tmpfs:
    - /tmp
    - /run
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    # register to the self-hosted runner group allowed on public repositories
    ACTIONS_RUNNER_GROUP: self-hosted
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io

services:

  # container runners are only suitable for private repositories

  runner-container:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.14.4

  # focal-vm is the equivalent of ubuntu-20.04

  runner-focal:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3-focal

  # jammy-vm is the equivalent of ubuntu-22.04(-latest)

  runner-jammy-1:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  runner-jammy-2:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  runner-jammy-3:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  runner-jammy-4:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  runner-jammy-5:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  runner-jammy-6:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  runner-jammy-7:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  runner-jammy-8:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.7.3

  # inspects the runner logs and sets the supervisor lock if jobs are running
  lock-manager:
    build: lock-manager
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena-engine.sock
