version: "2.4"

x-runner-container:
  &runner-container
  privileged: true
  labels:
    # Allow CI pipelines to load kernel modules on the host
    io.balena.features.kernel-modules: '1'
  tmpfs:
    - /tmp
    - /run
    - /scratch
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    DOCKER_REGISTRY_MIRROR: http://registry-cache:5000
    INSECURE_REGISTRY: registry-cache:5000
    # container runners are only suitable for private repositories
    ACTIONS_RUNNER_GROUP: self-hosted-internal

x-runner-vm:
  &runner-vm
  cap_drop:
    - ALL
  cap_add:
    - NET_RAW # Required for VM networking
    - NET_ADMIN # Required for VM networking
    - CHOWN # Required to change ownership of files
    - DAC_OVERRIDE # Required by confd
  devices:
    - /dev/kvm # Required for Firecracker virtualization
    - /dev/net/tun # Required to create TAP/TUN device
  sysctls:
    - net.ipv4.ip_forward=1 # Required for VM networking
  tmpfs:
    - /tmp
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    DOCKER_REGISTRY_MIRROR: http://registry-cache:5000
    INSECURE_REGISTRY: registry-cache:5000
    ACTIONS_RUNNER_GROUP: self-hosted

services:

  runner-container-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:4.0.10

  runner-container-2:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:4.0.10

  runner-focal-1:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2-focal

  runner-focal-2:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2-focal

  runner-jammy-1:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2

  runner-jammy-2:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2

  runner-jammy-3:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2

  runner-jammy-4:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2

  runner-jammy-5:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2

  runner-jammy-6:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:1.1.2

  # https://distribution.github.io/distribution/recipes/mirror/
  registry-cache:
    image: registry:2.8.3
    volumes:
      - registry-data:/var/lib/registry
    tmpfs:
      - /tmp
      - /run
    environment:
      # Listen on the default bridge network on port 5000.
      # Do not expose this unsecured port on the host network!
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
      # The proxy.ttl setting isn't supported until registry v3 but we can set it now and it will be ignored
      # https://github.com/distribution/distribution/blob/5d5c60f77c01b143b22be9d62af3b32843fbcb0c/configuration/configuration.go#L643-L653
      # https://github.com/distribution/distribution/blob/e1ec19ae60b8628b564d4fb01ce09ef81047987c/configuration/configuration.go#L628-L643
      REGISTRY_PROXY_TTL: 168h
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      # REGISTRY_PROXY_USERNAME: changeme
      # REGISTRY_PROXY_PASSWORD: changeme
      # REGISTRY_LOG_LEVEL: debug

volumes:
  registry-data: {}
