version: "2.4"

x-runner-container:
  &runner-container
  privileged: true
  tmpfs:
    - /tmp
    - /run
    - /scratch
  environment:
    GITHUB_ENTERPRISE: balena
    # register to the internal-only self-hosted runner group
    ACTIONS_RUNNER_GROUP: self-hosted-internal

x-runner-vm:
  &runner-vm
  privileged: true
  network_mode: host
  tmpfs:
    - /tmp
    - /run
    - /srv
  environment:
    GITHUB_ENTERPRISE: balena
    # register to the self-hosted runner group allowed on public repositories
    ACTIONS_RUNNER_GROUP: self-hosted
    # limit VM memory to 32GB, or the host total memory, whichever is lower
    MEM_SIZE_MIB: 32768

services:

  runner-jammy-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.87

  runner-jammy-2:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.87

  runner-focal-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.87-focal

  runner-focal-2:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.8.87-focal

  runner-jammy-vm-1:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.87-jammy-vm

  runner-jammy-vm-2:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.87-jammy-vm

  runner-focal-vm-1:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.87-focal-vm

  runner-focal-vm-2:
    <<: *runner-vm
    image: ghcr.io/product-os/self-hosted-runners:3.8.87-focal-vm

  lock-manager:
    build: lock-manager
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena-engine.sock
