version: "2.4"

x-runner-container:
  &runner-container
  privileged: true
  tmpfs:
    - /tmp
    - /run
    - /scratch
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    # register to the internal-only self-hosted runner group
    ACTIONS_RUNNER_GROUP: self-hosted-internal
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io

x-runner-vm:
  &runner-vm
  privileged: true
  network_mode: host
  tmpfs:
    - /tmp
    - /run
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    # register to the self-hosted runner group allowed on public repositories
    ACTIONS_RUNNER_GROUP: self-hosted
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io
    # limit VM memory to 32GB, or the host total memory, whichever is lower
    MEM_SIZE_MIB: 32768

services:

  # container runners are only suitable for private repositories

  jammy-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.11.12

  focal-1:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.11.12-focal

  # focal-vm is the equivalent of ubuntu-20.04

  focal-vm-1:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31-focal

  focal-vm-2:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31-focal

  # jammy-vm is the equivalent of ubuntu-22.04(-latest)

  jammy-vm-1:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  jammy-vm-2:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  jammy-vm-3:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  jammy-vm-4:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  jammy-vm-5:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  jammy-vm-6:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  jammy-vm-7:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  jammy-vm-8:
    <<: *runner-vm
    image: ghcr.io/product-os/github-runner-vm:0.2.31

  # inspects the runner logs and sets the supervisor lock if jobs are running
  lock-manager:
    build: lock-manager
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena-engine.sock
