version: "2.4"

x-runner-container:
  &runner-container
  privileged: true
  tmpfs:
    - /tmp
    - /run
    - /scratch
  # limit container runners to 15% of CPU resources
  cpu_quota: 15000
  # limit container runners to 8g of RAM
  mem_limit: 8g
  environment:
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io
    # container runners are only suitable for private repositories
    ACTIONS_RUNNER_GROUP: self-hosted-internal

x-runner-vm:
  &runner-vm
  privileged: true
  network_mode: host
  tmpfs:
    - /tmp
    - /run
  environment: &runner-env
    ACTIONS_RUNNER_REGISTRATION_SLUG: enterprises/balena
    DOCKER_REGISTRY_MIRROR: https://nfs.product-os.io
    ACTIONS_RUNNER_GROUP: self-hosted

# large runners with 2 vCPUs and 4GiB of memory
x-runner-large: &runner-large
  <<: *runner-vm
  environment:
    <<: *runner-env
    VCPU_COUNT: 2
    MEMORY_SIZE_GIB: 4

# xlarge runners with 4 vCPUs and 8GiB of memory
x-runner-xlarge: &runner-xlarge
  <<: *runner-vm
  environment:
    <<: *runner-env
    VCPU_COUNT: 4
    MEMORY_SIZE_GIB: 8

# xlarge runners with 8 vCPUs and 16GiB of memory
x-runner-2xlarge: &runner-2xlarge
  <<: *runner-vm
  environment:
    <<: *runner-env
    VCPU_COUNT: 8
    MEMORY_SIZE_GIB: 16

# 4xlarge runners with 16 vCPUs and 32GiB of memory
x-runner-4xlarge: &runner-4xlarge
  <<: *runner-vm
  environment:
    <<: *runner-env
    VCPU_COUNT: 16
    MEMORY_SIZE_GIB: 32

services:

  runner-container:
    <<: *runner-container
    image: ghcr.io/product-os/self-hosted-runners:3.14.5

  runner-focal:
    <<: *runner-large
    image: ghcr.io/product-os/github-runner-vm:0.7.7-focal

  runner-large-1:
    <<: *runner-large
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  runner-large-2:
    <<: *runner-large
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  runner-xlarge-1:
    <<: *runner-xlarge
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  runner-xlarge-2:
    <<: *runner-xlarge
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  runner-4xlarge-1:
    <<: *runner-4xlarge
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  runner-4xlarge-2:
    <<: *runner-4xlarge
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  runner-4xlarge-3:
    <<: *runner-4xlarge
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  runner-4xlarge-4:
    <<: *runner-4xlarge
    image: ghcr.io/product-os/github-runner-vm:0.7.7

  # inspects the runner logs and sets the supervisor lock if jobs are running
  lock-manager:
    build: lock-manager
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena-engine.sock
