version: "2.4"

services:
  builder:
    <<: *builder-common
    image: ghcr.io/balena-io/balena-builder-worker:0.8.8-amd64
    ports:
      - 2376:2376
    networks:
      - builder
    volumes:
      - builder:/var/lib/balena-engine
      - certs:/certs:ro

  runner-jammy-1:
    <<: *runner-common
    image: ghcr.io/product-os/self-hosted-runners:3.1.5-amd64
    networks:
      - runner-jammy-1

  runner-jammy-2:
    <<: *runner-common
    image: ghcr.io/product-os/self-hosted-runners:3.1.5-amd64
    networks:
      - runner-jammy-2

  runner-focal-1:
    <<: *runner-common
    image: ghcr.io/product-os/self-hosted-runners:3.1.5-focal-amd64
    networks:
      - runner-focal-1

  runner-focal-2:
    <<: *runner-common
    image: ghcr.io/product-os/self-hosted-runners:3.1.5-focal-amd64
    networks:
      - runner-focal-2

  cert-manager:
    <<: *cert-manager-common

  qemu-user-static:
    <<: *qemu-user-static-common

# isolate container networks for security
networks:
  builder: {}
  runner-jammy-1: {}
  runner-jammy-2: {}
  runner-focal-1: {}
  runner-focal-2: {}

volumes:
  builder: {}
  cert-manager: {}
  certs: {}
